workflows:
  build-debug-apk:
    name: Build Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug --target-platform android-arm,android-arm64
          echo "=== Build folder structure ==="
          ls -R build/ || true
    artifacts:
      # مسیرهای معمول Flutter
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/apk/debug/app-debug.apk
      # مسیرهای جدید (native_assets)
      - build/native_assets/android/**/*.apk
      - build/native_assets/**/*.apk
    publishing:
      email:
        recipients:
          - ehsan.system67@gmail.com
